import { Whisky } from "./data";

export const globalWhiskies: Partial<Whisky>[] = [
    { id: "g1", name: "Laphroaig 10 Year Old", type: "Single Malt", region: "Islay, Scotland", basePrice: 60, currency: "USD", tags: ["smoky", "medicinal", "라프로익", "피트"] },
    { id: "g2", name: "Macallan 12 Year Old Sherry Oak", type: "Single Malt", region: "Speyside, Scotland", basePrice: 100, currency: "USD", tags: ["sherry", "classic", "맥켈란", "셰리"] },
    { id: "g3", name: "Lagavulin 16 Year Old", type: "Single Malt", region: "Islay, Scotland", basePrice: 105, currency: "USD", tags: ["smoky", "rich", "라가불린", "피트"] },
    { id: "g4", name: "Ardbeg 10 Year Old", type: "Single Malt", region: "Islay, Scotland", basePrice: 65, currency: "USD", tags: ["smoky", "complex", "아드벡", "피트"] },
    { id: "g5", name: "Glenfiddich 12 Year Old", type: "Single Malt", region: "Speyside, Scotland", basePrice: 50, currency: "USD", tags: ["pear", "fresh", "글렌피딕", "싱글몰트"] },
    { id: "g6", name: "The Balvenie 12 Year Old DoubleWood", type: "Single Malt", region: "Speyside, Scotland", basePrice: 70, currency: "USD", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ea/The_Balvenie_DoubleWood.jpg", tags: ["honey", "vanilla", "발베니", "꿀"] },
    { id: "g7", name: "Highland Park 12 Year Old", type: "Single Malt", region: "Orkney, Scotland", basePrice: 55, currency: "USD", tags: ["balanced", "heather", "하이랜드파크"] },
    { id: "g8", name: "Talisker 10 Year Old", type: "Single Malt", region: "Isle of Skye, Scotland", basePrice: 70, currency: "USD", tags: ["pepper", "sea salt", "탈리스커", "피트"] },
    { id: "g9", name: "Glenmorangie 10 Year Old", type: "Single Malt", region: "Highland, Scotland", basePrice: 45, currency: "USD", tags: ["floral", "peach", "글렌모린지"] },
    { id: "g10", name: "Oban 14 Year Old", type: "Single Malt", region: "Highland, Scotland", basePrice: 90, currency: "USD", visualProfile: { bottleShape: "tall", liquidColor: "gold", glassColor: "clear" }, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/87/Oban_14yo.jpg", tags: ["dry", "coastal", "오반"] },
    { id: "g11", name: "Hibiki Japanese Harmony", type: "Blended", region: "Japan", basePrice: 110, currency: "USD", visualProfile: { bottleShape: "faceted", liquidColor: "gold", glassColor: "clear" }, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Hibiki_the_premium_blended_whisky_from_Japanese_distiller_Suntory.jpg/800px-Hibiki_the_premium_blended_whisky_from_Japanese_distiller_Suntory.jpg", tags: ["floral", "elegant", "히비키", "하모니"] },
    { id: "g12", name: "Yamazaki 12 Year Old", type: "Single Malt", region: "Japan", basePrice: 180, currency: "USD", tags: ["sandalwood", "fruit", "야마자키"] },
    { id: "g13", name: "Nikka from the Barrel", type: "Blended", region: "Japan", basePrice: 75, currency: "USD", tags: ["strong", "spicy", "니카"] },
    { id: "g14", name: "Buffalo Trace", type: "Bourbon", region: "Kentucky, USA", basePrice: 35, currency: "USD", tags: ["vanilla", "smooth", "버팔로트레이스", "버번"] },
    { id: "g15", name: "Eagle Rare 10 Year Old", type: "Bourbon", region: "Kentucky, USA", basePrice: 60, currency: "USD", tags: ["toffee", "oak", "이글레어", "버번"] },
    { id: "g16", name: "Blanton's Single Barrel", type: "Bourbon", region: "Kentucky, USA", basePrice: 90, currency: "USD", tags: ["premium", "horse", "블랑톤", "버번"] },
    { id: "g17", name: "Woodford Reserve", type: "Bourbon", region: "Kentucky, USA", basePrice: 40, currency: "USD", tags: ["rich", "cocoa", "우드포드리저브", "버번"] },
    { id: "g18", name: "Maker's Mark", type: "Bourbon", region: "Kentucky, USA", basePrice: 35, currency: "USD", tags: ["wheat", "soft", "메이커스마크", "버번"] },
    { id: "g19", name: "Johnnie Walker Black Label", type: "Blended Scotch", region: "Scotland", basePrice: 40, currency: "USD", tags: ["balanced", "smoky", "조니워커", "블랙"] },
    { id: "g20", name: "Johnnie Walker Blue Label", type: "Blended Scotch", region: "Scotland", basePrice: 220, currency: "USD", tags: ["luxury", "rare", "조니워커", "블루"] },
    { id: "g21", name: "Jameson Irish Whiskey", type: "Blended", region: "Ireland", basePrice: 35, currency: "USD", tags: ["smooth", "light", "제임슨"] },
    { id: "g22", name: "Redbreast 12 Year Old", type: "Single Pot Still", region: "Ireland", basePrice: 70, currency: "USD", tags: ["creamy", "spice", "레드브레스트"] },
    { id: "g23", name: "Green Spot", type: "Single Pot Still", region: "Ireland", basePrice: 65, currency: "USD", tags: ["fruity", "green apple", "그린스팟"] },
    { id: "g24", name: "Caol Ila 12 Year Old", type: "Single Malt", region: "Islay, Scotland", basePrice: 70, currency: "USD", tags: ["smoke", "lemon", "쿠일라", "피트"] },
    { id: "g25", name: "Bowmore 12 Year Old", type: "Single Malt", region: "Islay, Scotland", basePrice: 60, currency: "USD", tags: ["peat", "honey", "보모어", "피트"] },
    { id: "g26", name: "Bruichladdich Classic Laddie", type: "Single Malt", region: "Islay, Scotland", basePrice: 65, currency: "USD", tags: ["unpeated", "islay", "브룩라디"] },
    { id: "g27", name: "Aberlour 12 Year Old", type: "Single Malt", region: "Speyside, Scotland", basePrice: 60, currency: "USD", tags: ["double cask", "smooth", "아벨라워"] },
    { id: "g28", name: "Glenlivet 12 Year Old", type: "Single Malt", region: "Speyside, Scotland", basePrice: 50, currency: "USD", tags: ["floral", "classic", "글렌리벳"] },
    { id: "g29", name: "Dalmore 12 Year Old", type: "Single Malt", region: "Highland, Scotland", basePrice: 80, currency: "USD", tags: ["orange", "rich", "달모어"] },
    { id: "g30", name: "Old Pulteney 12 Year Old", type: "Single Malt", region: "Highland, Scotland", basePrice: 50, currency: "USD", tags: ["brine", "maritime", "올드펄트니"] },
    { id: "g31", name: "Springbank 10 Year Old", type: "Single Malt", region: "Campbeltown, Scotland", basePrice: 90, currency: "USD", tags: ["craft", "complex", "스프링뱅크"] },
    { id: "g32", name: "Glenfarclas 12 Year Old", type: "Single Malt", region: "Speyside, Scotland", basePrice: 55, currency: "USD", tags: ["sherry", "family", "글렌파클라스"] },
    { id: "g33", name: "Bunnahabhain 12 Year Old", type: "Single Malt", region: "Islay, Scotland", basePrice: 65, currency: "USD", tags: ["rich", "nutty", "부나하벤"] },
    { id: "g34", name: "Kilchoman Machir Bay", type: "Single Malt", region: "Islay, Scotland", basePrice: 65, currency: "USD", tags: ["farm", "smoke", "킬호만"] },
    { id: "g35", name: "Suntory Toki", type: "Blended", region: "Japan", basePrice: 40, currency: "USD", tags: ["highball", "light", "산토리", "토키"] },
    { id: "g36", name: "Nikka Coffey Grain", type: "Grain Whisky", region: "Japan", basePrice: 75, currency: "USD", tags: ["sweet", "bourbon-like", "니카"] },
    { id: "g37", name: "Bulleit Bourbon", type: "Bourbon", region: "Kentucky, USA", basePrice: 35, currency: "USD", tags: ["rye-heavy", "spicy", "불렛", "버번"] },
    { id: "g38", "name": "Wild Turkey 101", type: "Bourbon", region: "Kentucky, USA", basePrice: 30, currency: "USD", tags: ["kick", "classic", "와일드터키", "버번"] },
    { id: "g39", "name": "Knob Creek 9 Year", type: "Bourbon", region: "Kentucky, USA", basePrice: 40, currency: "USD", tags: ["full-bodied", "oak", "놉크릭", "버번"] },
    { id: "g40", "name": "Basil Hayden's", type: "Bourbon", region: "Kentucky, USA", basePrice: 45, currency: "USD", tags: ["light", "elegant", "바질헤이든", "버번"] },
    { id: "g41", "name": "Michter's US*1 Bourbon", type: "Bourbon", region: "Kentucky, USA", basePrice: 50, currency: "USD", tags: ["small batch", "rich", "믹터스", "버번"] },
    { id: "g42", "name": "Elijah Craig Small Batch", type: "Bourbon", region: "Kentucky, USA", basePrice: 35, currency: "USD", tags: ["classic", "sweet", "엘라이저크레이그", "버번"] },
    { id: "g43", "name": "Jack Daniel's No. 7", type: "Tennessee Whiskey", region: "Tennessee, USA", basePrice: 30, currency: "USD", tags: ["iconic", "charcoal", "잭다니엘"] },
    { id: "g44", "name": "George Dickel No. 12", type: "Tennessee Whiskey", region: "Tennessee, USA", basePrice: 35, currency: "USD", tags: ["smooth", "mineral", "조지디켈"] },
    { id: "g45", "name": "Tullamore D.E.W.", type: "Blended", region: "Ireland", basePrice: 30, currency: "USD", tags: ["triple distilled", "smooth", "툴라모어"] },
    { id: "g46", "name": "Bushmills Black Bush", type: "Blended", region: "Ireland", basePrice: 40, currency: "USD", tags: ["sherry", "rich", "부쉬밀"] },
    { id: "g47", "name": "Teeling Small Batch", type: "Blended", region: "Ireland", basePrice: 40, currency: "USD", tags: ["rum cask", "sweet", "틸링"] },
    { id: "g48", "name": "Kavalan Classic", type: "Single Malt", region: "Taiwan", basePrice: 90, currency: "USD", tags: ["tropical", "subtropical", "카발란"] },
    { id: "g49", "name": "Amrut Fusion", type: "Single Malt", region: "India", basePrice: 70, currency: "USD", tags: ["smoke", "spice", "암룬"] },
    { id: "g50", "name": "Paul John Edited", type: "Single Malt", region: "India", basePrice: 65, currency: "USD", tags: ["soft smoke", "honey", "폴존"] },
    { id: "g51", "name": "Glendronach 12 Year", type: "Single Malt", region: "Highland, Scotland", basePrice: 65, currency: "USD", tags: ["sherry bomb", "rich", "글렌드로낙"] },
    { id: "g52", "name": "Arran 10 Year Old", type: "Single Malt", region: "Isle of Arran, Scotland", basePrice: 60, currency: "USD", tags: ["citrus", "unpeated", "아란"] },
    { id: "g53", "name": "Jura 10 Year Old", type: "Single Malt", region: "Isle of Jura, Scotland", basePrice: 50, currency: "USD", tags: ["smoke", "sweet", "쥬라"] },
    { id: "g54", "name": "Clynelish 14 Year Old", type: "Single Malt", region: "Highland, Scotland", basePrice: 85, currency: "USD", tags: ["waxy", "honey", "클라이넬리쉬"] },
    { id: "g55", "name": "Mortlach 12 Year Old", type: "Single Malt", region: "Speyside, Scotland", basePrice: 75, currency: "USD", tags: ["beast of dufftown", "meaty", "모틀락"] },
    { id: "g56", "name": "Benriach The Twelve", type: "Single Malt", region: "Speyside, Scotland", basePrice: 60, currency: "USD", tags: ["complex", "sherry", "벤리악"] },
    { id: "g57", "name": "Craigellachie 13 Year", type: "Single Malt", region: "Speyside, Scotland", basePrice: 65, currency: "USD", tags: ["sulfuric", "bold", "크라이겔라키"] },
    { id: "g58", "name": "Deanston 12 Year Old", type: "Single Malt", region: "Highland, Scotland", basePrice: 60, currency: "USD", tags: ["waxy", "honey", "딘스톤"] },
    { id: "g59", "name": "Glengoyne 12 Year Old", type: "Single Malt", region: "Highland, Scotland", basePrice: 60, currency: "USD", tags: ["unpeated", "sherry", "글렌고인"] },
    { id: "g60", "name": "Royal Brackla 12 Year", type: "Single Malt", region: "Highland, Scotland", basePrice: 75, currency: "USD", tags: ["royal", "elegant", "로얄브라클라"] },
    { id: "g61", "name": "Hakushu 12 Year Old", type: "Single Malt", region: "Japan", basePrice: 180, currency: "USD", tags: ["forest", "mint", "하쿠슈"] },
    { id: "g62", "name": "Yoichi Single Malt", type: "Single Malt", region: "Japan", basePrice: 100, currency: "USD", tags: ["coastal", "smoke", "요이치"] },
    { id: "g63", "name": "Miyagikyo Single Malt", type: "Single Malt", region: "Japan", basePrice: 100, currency: "USD", tags: ["floral", "soft", "미야기쿄"] },
    { id: "g64", "name": "Four Roses Single Barrel", type: "Bourbon", region: "Kentucky, USA", basePrice: 50, currency: "USD", tags: ["spicy", "fruit", "포로지스"] },
    { id: "g65", "name": "Russell's Reserve 10 Year", type: "Bourbon", region: "Kentucky, USA", basePrice: 40, currency: "USD", tags: ["classic", "rich", "러셀"] },
    { id: "g66", "name": "Angel's Envy Bourbon", type: "Bourbon", region: "Kentucky, USA", basePrice: 55, currency: "USD", tags: ["port finish", "sweet", "엔젤스엔비"] },
    { id: "g67", "name": "Booker's Bourbon", type: "Bourbon", region: "Kentucky, USA", basePrice: 100, currency: "USD", tags: ["cask strength", "bold", "부커스"] },
    { id: "g68", "name": "Stagg Jr.", type: "Bourbon", region: "Kentucky, USA", basePrice: 80, currency: "USD", tags: ["intense", "rare", "스태그"] },
    { id: "g69", "name": "WhistlePig 10 Year Rye", type: "Rye", region: "Vermont, USA", basePrice: 80, currency: "USD", tags: ["rye", "premium", "휘슬피그"] },
    { id: "g70", "name": "High West Rendezvous Rye", type: "Rye", region: "Utah, USA", basePrice: 75, currency: "USD", tags: ["bend", "spicy", "하이웨스트"] },
    { id: "g71", "name": "Sazerac Rye", type: "Rye", region: "Kentucky, USA", basePrice: 40, currency: "USD", tags: ["classic", "cocktail", "사제락"] },
    { id: "g72", "name": "Rittenhouse Rye", type: "Rye", region: "Kentucky, USA", basePrice: 30, currency: "USD", tags: ["strong", "bonded", "리텐하우스"] },
    { id: "g73", "name": "Lot 40 Rye", type: "Rye", region: "Canada", basePrice: 40, currency: "USD", tags: ["canadian", "grain", "롯40"] },
    { id: "g74", "name": "Crown Royal Deluxe", type: "Blended", region: "Canada", basePrice: 30, currency: "USD", tags: ["smooth", "velvet", "크라운로얄"] },
    { id: "g75", "name": "Glenmorangie 14 Quinta Ruban", type: "Single Malt", region: "Highland, Scotland", basePrice: 70, currency: "USD", tags: ["port finish", "chocolate", "글렌모린지"] },
    { id: "g76", "name": "Aberlour A'bunadh", type: "Single Malt", region: "Speyside, Scotland", basePrice: 100, currency: "USD", tags: ["cask strength", "sherry bomb", "아벨라워"] },
    { id: "g77", "name": "Laphroaig Lore", type: "Single Malt", region: "Islay, Scotland", basePrice: 130, currency: "USD", tags: ["complex", "rich smoke", "라프로익"] },
    { id: "g78", "name": "Ardbeg Uigeadail", type: "Single Malt", region: "Islay, Scotland", basePrice: 90, currency: "USD", tags: ["smoke", "sherry", "아드벡"] },
    { id: "g79", "name": "Lagavulin 8 Year Old", type: "Single Malt", region: "Islay, Scotland", basePrice: 70, currency: "USD", tags: ["fresh smoke", "islay", "라가불린"] },
    { id: "g80", "name": "Port Charlotte 10", type: "Single Malt", region: "Islay, Scotland", basePrice: 75, currency: "USD", tags: ["heavily peated", "bruichladdich", "포트샬롯"] },
    { id: "g81", "name": "Chivas Regal 12 Year Old", type: "Blended Scotch", region: "Scotland", basePrice: 35, currency: "USD", tags: ["classic", "smooth", "시바스리갈"] },
    { id: "g82", name: "Dewars 12 Year Old", type: "Blended Scotch", region: "Scotland", basePrice: 35, currency: "USD", tags: ["balanced", "double aged", "듀어스"] },
    { id: "g83", name: "Monkey Shoulder", type: "Blended Malt", region: "Scotland", basePrice: 35, currency: "USD", visualProfile: { bottleShape: "stout", liquidColor: "gold", glassColor: "clear" }, imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Monkey_Shoulder_scotch_bottle.jpg", tags: ["malty", "cocktail", "몽키숄더"] },
    { id: "g84", "name": "Compass Box Hedonism", type: "Blended Grain", region: "Scotland", basePrice: 110, currency: "USD", tags: ["creamy", "grain", "컴파스박스"] },
    { id: "g85", "name": "Powers Gold Label", type: "Blended", region: "Ireland", basePrice: 35, currency: "USD", tags: ["classic", "irish", "파워스"] },
    { id: "g86", "name": "Writers' Tears Copper Pot", type: "Blended", region: "Ireland", basePrice: 45, currency: "USD", tags: ["pot still", "smooth", "라이터스 티어스"] },
    { id: "g87", "name": "Roe & Co", type: "Blended", region: "Ireland", basePrice: 40, currency: "USD", tags: ["modern", "smooth", "로앤코"] },
    { id: "g88", "name": "Penderyn Madeira Finish", type: "Single Malt", region: "Wales", basePrice: 65, currency: "USD", tags: ["welsh", "fruity", "펜더린"] },
    { id: "g89", "name": "Mackmyra Svensk Ek", type: "Single Malt", region: "Sweden", basePrice: 70, currency: "USD", tags: ["swedish", "oak", "맥미라"] },
    { id: "g90", "name": "Starward Nova", type: "Single Malt", region: "Australia", basePrice: 65, currency: "USD", tags: ["wine cask", "modern", "스타워드"] },
    { id: "g91", "name": "Hakushu Distiller's Reserve", type: "Single Malt", region: "Japan", basePrice: 110, currency: "USD", tags: ["green", "fresh", "하쿠슈"] },
    { id: "g92", "name": "Yamazaki Distiller's Reserve", type: "Single Malt", region: "Japan", basePrice: 110, currency: "USD", tags: ["berry", "oak", "야마자키"] },
    { id: "g93", "name": "Nikka Days", type: "Blended", region: "Japan", basePrice: 50, currency: "USD", tags: ["everyday", "clean", "니카"] },
    { id: "g94", "name": "Evan Williams Single Barrel", type: "Bourbon", region: "Kentucky, USA", basePrice: 35, currency: "USD", tags: ["vintage", "classic", "에반윌리엄스"] },
    { id: "g95", "name": "Jefferson's Ocean", type: "Bourbon", region: "USA", basePrice: 90, currency: "USD", tags: ["aged at sea", "unique", "제퍼슨스오션"] },
    { id: "g96", "name": "Old Forester 1920", type: "Bourbon", region: "Kentucky, USA", basePrice: 60, currency: "USD", tags: ["prohibition", "strong", "올드포레스터"] },
    { id: "g97", "name": "Weller Special Reserve", type: "Bourbon", region: "Kentucky, USA", basePrice: 50, currency: "USD", tags: ["wheated", "rare", "웰러"] },
    { id: "g98", "name": "1792 Small Batch", type: "Bourbon", region: "Kentucky, USA", basePrice: 35, currency: "USD", tags: ["rye-forward", "bold", "1791"] },
    { id: "g99", "name": "Glen Grant 12 Year Old", type: "Single Malt", region: "Speyside, Scotland", basePrice: 50, currency: "USD", tags: ["floral", "light", "글렌그란트"] },
    { id: "g100", "name": "Tobermory 12 Year Old", type: "Single Malt", region: "Isle of Mull, Scotland", basePrice: 60, currency: "USD", tags: ["unpeated", "islands", "토버모리"] },
];
