import { Whisky } from "./data";

export const globalWhiskies: Partial<Whisky>[] = [
    // g7(Highland Park 12), g12(Yamazaki 12), g13(Nikka from the Barrel), 
    // g15(Eagle Rare 10), g16(Blanton), g22(Redbreast 12), g23(Green Spot), 
    // g24(Caol Ila 12), g29(Dalmore 12), g30(Old Pulteney 12), g33(Bunnahabhain 12),
    // g34(Kilchoman Machir Bay), g35(Suntory Toki), g37(Bulleit Bourbon) 은 data.ts에 이미 존재하므로 제거함.

    { id: "g20", name: "Johnnie Walker Blue Label", type: "Blended Scotch", region: "Scotland", basePrice: 220, currency: "USD", imageUrl: "", tags: ["luxury", "rare", "조니워커", "블루"] },
    { id: "g21", name: "Jameson Irish Whiskey", type: "Blended", region: "Ireland", basePrice: 35, currency: "USD", tags: ["smooth", "light", "제임슨"] },
    { id: "g26", name: "Bruichladdich Classic Laddie", type: "Single Malt", region: "Islay, Scotland", basePrice: 65, currency: "USD", tags: ["unpeated", "islay", "브룩라디"] },
    { id: "g27", name: "Aberlour 12 Year Old", type: "Single Malt", region: "Speyside, Scotland", basePrice: 60, currency: "USD", tags: ["double cask", "smooth", "아벨라워"] },
    { id: "g28", name: "Glenlivet 12 Year Old", type: "Single Malt", region: "Speyside, Scotland", basePrice: 50, currency: "USD", tags: ["floral", "classic", "글렌리벳"] },
    { id: "g31", name: "Springbank 10 Year Old", type: "Single Malt", region: "Campbeltown, Scotland", basePrice: 90, currency: "USD", tags: ["craft", "complex", "스프링뱅크"] },
    { id: "g32", name: "Glenfarclas 12 Year Old", type: "Single Malt", region: "Speyside, Scotland", basePrice: 55, currency: "USD", tags: ["sherry", "family", "글렌파클라스"] },
    { id: "g36", name: "Nikka Coffey Grain", type: "Grain Whisky", region: "Japan", basePrice: 75, currency: "USD", tags: ["sweet", "bourbon-like", "니카"] },
    { id: "g39", "name": "Knob Creek 9 Year", type: "Bourbon", region: "Kentucky, USA", basePrice: 40, currency: "USD", tags: ["full-bodied", "oak", "놉크릭", "버번"] },
    { id: "g40", "name": "Basil Hayden's", type: "Bourbon", region: "Kentucky, USA", basePrice: 45, currency: "USD", tags: ["light", "elegant", "바질헤이든", "버번"] },
    { id: "g41", "name": "Michter's US*1 Bourbon", type: "Bourbon", region: "Kentucky, USA", basePrice: 50, currency: "USD", tags: ["small batch", "rich", "믹터스", "버번"] },
    { id: "g42", "name": "Elijah Craig Small Batch", type: "Bourbon", region: "Kentucky, USA", basePrice: 35, currency: "USD", tags: ["classic", "sweet", "엘라이저크레이그", "버번"] },
    { id: "g43", "name": "Jack Daniel's No. 7", type: "Tennessee Whiskey", region: "Tennessee, USA", basePrice: 30, currency: "USD", tags: ["iconic", "charcoal", "잭다니엘"] },
    { id: "g44", "name": "George Dickel No. 12", type: "Tennessee Whiskey", region: "Tennessee, USA", basePrice: 35, currency: "USD", tags: ["smooth", "mineral", "조지디켈"] },
    { id: "g45", "name": "Tullamore D.E.W.", type: "Blended", region: "Ireland", basePrice: 30, currency: "USD", tags: ["triple distilled", "smooth", "툴라모어"] },
    { id: "g46", "name": "Bushmills Black Bush", type: "Blended", region: "Ireland", basePrice: 40, currency: "USD", tags: ["sherry", "rich", "부쉬밀"] },
    { id: "g47", "name": "Teeling Small Batch", type: "Blended", region: "Ireland", basePrice: 40, currency: "USD", tags: ["rum cask", "sweet", "틸링"] },
    { id: "g48", "name": "Kavalan Classic", type: "Single Malt", region: "Taiwan", basePrice: 90, currency: "USD", tags: ["tropical", "subtropical", "카발란"] },
    { id: "g49", "name": "Amrut Fusion", type: "Single Malt", region: "India", basePrice: 70, currency: "USD", tags: ["smoke", "spice", "암룬"] },
    { id: "g50", "name": "Paul John Edited", type: "Single Malt", region: "India", basePrice: 65, currency: "USD", tags: ["soft smoke", "honey", "폴존"] },
    { id: "g52", "name": "Arran 10 Year Old", type: "Single Malt", region: "Isle of Arran, Scotland", basePrice: 60, currency: "USD", tags: ["citrus", "unpeated", "아란"] },
    { id: "g53", "name": "Jura 10 Year Old", type: "Single Malt", region: "Isle of Jura, Scotland", basePrice: 50, currency: "USD", tags: ["smoke", "sweet", "쥬라"] },
    { id: "g54", "name": "Clynelish 14 Year Old", type: "Single Malt", region: "Highland, Scotland", basePrice: 85, currency: "USD", tags: ["waxy", "honey", "클라이넬리쉬"] },
    { id: "g55", "name": "Mortlach 12 Year Old", type: "Single Malt", region: "Speyside, Scotland", basePrice: 75, currency: "USD", tags: ["beast of dufftown", "meaty", "모틀락"] },
    { id: "g56", "name": "Benriach The Twelve", type: "Single Malt", region: "Speyside, Scotland", basePrice: 60, currency: "USD", tags: ["complex", "sherry", "벤리악"] },
    { id: "g57", "name": "Craigellachie 13 Year", type: "Single Malt", region: "Speyside, Scotland", basePrice: 65, currency: "USD", tags: ["sulfuric", "bold", "크라이겔라키"] },
    { id: "g58", "name": "Deanston 12 Year Old", type: "Single Malt", region: "Highland, Scotland", basePrice: 60, currency: "USD", tags: ["waxy", "honey", "딘스톤"] },
    { id: "g59", "name": "Glengoyne 12 Year Old", type: "Single Malt", region: "Highland, Scotland", basePrice: 60, currency: "USD", tags: ["unpeated", "sherry", "글렌고인"] },
    { id: "g60", "name": "Royal Brackla 12 Year", type: "Single Malt", region: "Highland, Scotland", basePrice: 75, currency: "USD", tags: ["royal", "elegant", "로얄브라클라"] },
    { id: "g61", "name": "Hakushu 12 Year Old", type: "Single Malt", region: "Japan", basePrice: 180, currency: "USD", tags: ["forest", "mint", "하쿠슈"] },
    { id: "g62", "name": "Yoichi Single Malt", type: "Single Malt", region: "Japan", basePrice: 100, currency: "USD", tags: ["coastal", "smoke", "요이치"] },
    { id: "g63", "name": "Miyagikyo Single Malt", type: "Single Malt", region: "Japan", basePrice: 100, currency: "USD", tags: ["floral", "soft", "미야기쿄"] },
    { id: "g64", "name": "Four Roses Single Barrel", type: "Bourbon", region: "Kentucky, USA", basePrice: 50, currency: "USD", tags: ["spicy", "fruit", "포로지스"] },
    { id: "g65", "name": "Russell's Reserve 10 Year", type: "Bourbon", region: "Kentucky, USA", basePrice: 40, currency: "USD", tags: ["classic", "rich", "러셀"] },
    { id: "g66", "name": "Angel's Envy Bourbon", type: "Bourbon", region: "Kentucky, USA", basePrice: 55, currency: "USD", tags: ["port finish", "sweet", "엔젤스엔비"] },
    { id: "g67", "name": "Booker's Bourbon", type: "Bourbon", region: "Kentucky, USA", basePrice: 100, currency: "USD", tags: ["cask strength", "bold", "부커스"] },
    { id: "g68", "name": "Stagg Jr.", type: "Bourbon", region: "Kentucky, USA", basePrice: 80, currency: "USD", tags: ["intense", "rare", "스태그"] },
    { id: "g69", "name": "WhistlePig 10 Year Rye", type: "Rye", region: "Vermont, USA", basePrice: 80, currency: "USD", tags: ["rye", "premium", "휘슬피그"] },
    { id: "g70", "name": "High West Rendezvous Rye", type: "Rye", region: "Utah, USA", basePrice: 75, currency: "USD", tags: ["bend", "spicy", "하이웨스트"] },
    { id: "g71", "name": "Sazerac Rye", type: "Rye", region: "Kentucky, USA", basePrice: 40, currency: "USD", tags: ["classic", "cocktail", "사제락"] },
    { id: "g72", "name": "Rittenhouse Rye", type: "Rye", region: "Kentucky, USA", basePrice: 30, currency: "USD", tags: ["strong", "bonded", "리텐하우스"] },
    { id: "g73", "name": "Lot 40 Rye", type: "Rye", region: "Canada", basePrice: 40, currency: "USD", tags: ["canadian", "grain", "롯40"] },
    { id: "g74", "name": "Crown Royal Deluxe", type: "Blended", region: "Canada", basePrice: 30, currency: "USD", tags: ["smooth", "velvet", "크라운로얄"] },
    { id: "g75", "name": "Glenmorangie 14 Quinta Ruban", type: "Single Malt", region: "Highland, Scotland", basePrice: 70, currency: "USD", tags: ["port finish", "chocolate", "글렌모린지"] },
    { id: "g76", "name": "Aberlour A'bunadh", type: "Single Malt", region: "Speyside, Scotland", basePrice: 100, currency: "USD", tags: ["cask strength", "sherry bomb", "아벨라워"] },
    { id: "g77", "name": "Laphroaig Lore", type: "Single Malt", region: "Islay, Scotland", basePrice: 130, currency: "USD", tags: ["complex", "rich smoke", "라프로익"] },
    { id: "g78", "name": "Ardbeg Uigeadail", type: "Single Malt", region: "Islay, Scotland", basePrice: 90, currency: "USD", tags: ["smoke", "sherry", "아드벡"] },
    { id: "g79", "name": "Lagavulin 8 Year Old", type: "Single Malt", region: "Islay, Scotland", basePrice: 70, currency: "USD", tags: ["fresh smoke", "islay", "라가불린"] },
    { id: "g80", "name": "Port Charlotte 10", type: "Single Malt", region: "Islay, Scotland", basePrice: 75, currency: "USD", tags: ["heavily peated", "bruichladdich", "포트샬롯"] },
    { id: "g81", "name": "Chivas Regal 12 Year Old", type: "Blended Scotch", region: "Scotland", basePrice: 35, currency: "USD", tags: ["classic", "smooth", "시바스리갈"] },
    { id: "g82", name: "Dewars 12 Year Old", type: "Blended Scotch", region: "Scotland", basePrice: 35, currency: "USD", tags: ["balanced", "double aged", "듀어스"] },
    { id: "g84", "name": "Compass Box Hedonism", type: "Blended Grain", region: "Scotland", basePrice: 110, currency: "USD", tags: ["creamy", "grain", "컴파스박스"] },
    { id: "g85", "name": "Powers Gold Label", type: "Blended", region: "Ireland", basePrice: 35, currency: "USD", tags: ["classic", "irish", "파워스"] },
    { id: "g86", "name": "Writers' Tears Copper Pot", type: "Blended", region: "Ireland", basePrice: 45, currency: "USD", tags: ["pot still", "smooth", "라이터스 티어스"] },
    { id: "g87", "name": "Roe & Co", type: "Blended", region: "Ireland", basePrice: 40, currency: "USD", tags: ["modern", "smooth", "로앤코"] },
    { id: "g88", "name": "Penderyn Madeira Finish", type: "Single Malt", region: "Wales", basePrice: 65, currency: "USD", tags: ["welsh", "fruity", "펜더린"] },
    { id: "g89", "name": "Mackmyra Svensk Ek", type: "Single Malt", region: "Sweden", basePrice: 70, currency: "USD", tags: ["swedish", "oak", "맥미라"] },
    { id: "g90", "name": "Starward Nova", type: "Single Malt", region: "Australia", basePrice: 65, currency: "USD", tags: ["wine cask", "modern", "스타워드"] },
    { id: "g91", "name": "Hakushu Distiller's Reserve", type: "Single Malt", region: "Japan", basePrice: 110, currency: "USD", tags: ["green", "fresh", "하쿠슈"] },
    { id: "g92", "name": "Yamazaki Distiller's Reserve", type: "Single Malt", region: "Japan", basePrice: 110, currency: "USD", tags: ["berry", "oak", "야마자키"] },
    { id: "g93", "name": "Nikka Days", type: "Blended", region: "Japan", basePrice: 50, currency: "USD", tags: ["everyday", "clean", "니카"] },
    { id: "g94", "name": "Evan Williams Single Barrel", type: "Bourbon", region: "Kentucky, USA", basePrice: 35, currency: "USD", tags: ["vintage", "classic", "에반윌리엄스"] },
    { id: "g95", "name": "Jefferson's Ocean", type: "Bourbon", region: "USA", basePrice: 90, currency: "USD", tags: ["aged at sea", "unique", "제퍼슨스오션"] },
    { id: "g96", "name": "Old Forester 1920", type: "Bourbon", region: "Kentucky, USA", basePrice: 60, currency: "USD", tags: ["prohibition", "strong", "올드포레스터"] },
    { id: "g97", "name": "Weller Special Reserve", type: "Bourbon", region: "Kentucky, USA", basePrice: 50, currency: "USD", tags: ["wheated", "rare", "웰러"] },
    { id: "g98", "name": "1792 Small Batch", type: "Bourbon", region: "Kentucky, USA", basePrice: 35, currency: "USD", tags: ["rye-forward", "bold", "1791"] },
    { id: "g99", "name": "Glen Grant 12 Year Old", type: "Single Malt", region: "Speyside, Scotland", basePrice: 50, currency: "USD", tags: ["floral", "light", "글렌그란트"] },
    { id: "g100", "name": "Tobermory 12 Year Old", type: "Single Malt", region: "Isle of Mull, Scotland", basePrice: 60, currency: "USD", tags: ["unpeated", "islands", "토버모리"] },
];
